# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 08:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20181108_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_caption',
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
