# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_remove_image_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
