# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20181114_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
